baseURL = 'https://rmitsuboshi.github.io'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
hasCJKLanguage = true
title = 'R. Mitsuboshi'
theme = 'beautifulhugo'


[Author]
name   = "R. Mitsuboshi"
github = "rmitsuboshi"


[[menu.main]]
    name = "HOME"
    url = "https://rmitsuboshi.github.io"
