baseURL = 'https://rmitsuboshi.github.io'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
hasCJKLanguage = true
title = 'R. Mitsuboshi'
theme = 'beautifulhugo'
github = 'https://github.com/rmitsuboshi'
