baseURL = 'https://rmitsuboshi.github.io'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
hasCJKLanguage = true
title = 'R. Mitsuboshi'
theme = 'beautifulhugo'

[Params.widgets.social]
github = 'rmitsuboshi'
