baseURL = 'https://rmitsuboshi.github.io'
languageCode = 'en'
defaultContentLanguage = 'en'
hasCJKLanguage = true
title = 'R. Mitsuboshi'
theme = 'beautifulhugo'
dateFormat = "January 1, 2023"


[Params]
mainSections = ["post"]


[Author]
name   = "R. Mitsuboshi"
github = "rmitsuboshi"
# reddit = "__leopardus__"
linkedin = "rmitsuboshi"


[[menu.main]]
    name = "ABOUT"
    url = "page/about"

